// app/constants/parts.ts
export const PART_LIST = [
  "Piccolo",
  "Flute",
  "Oboe",
  "Bassoon",
  "E♭ Clarinet",
  "Clarinet",
  "Bass Clarinet",
  "Soprano Saxophone",
  "Alto Saxophone",
  "Tenor Saxophone",
  "Baritone Saxophone",
  "Trumpet",
  "Mellophone",
  "French Horn",
  "Trombone",
  "Bass Trombone",
  "Baritone",
  "Euphonium",
  "Tuba",
  "Sousaphone",
  "Snare Drum",
  "Tenor Drums",
  "Bass Drum",
  "Cymbals",
  "Marimba",
  "Vibraphone",
  "Xylophone",
  "Glockenspiel",
  "Synthesizer",
  "Aux Percussion",
];
